name: Release

on:
  push:
    branches:
      - "fix/build-publish-npm"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 🚀 Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Configure NPM
        run: |
          npm config -g set @jondotsoy:registry https://registry.npmjs.org/
          npm config -g set //registry.npmjs.org/:_authToken ${{ secrets.NODE_AUTH_TOKEN }}
      - run: npm publish --tag latest
